[build]
  publish = "dist"
  command = "echo 'registry=https://registry.npmjs.org/' > .npmrc && npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
